name: Static analysis

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga:0.12.41
        env:
          REQUIRE_DEV: true
        with:
          args: analyze --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:2.16.4
        with:
          args: --dry-run --diff-format udiff
